# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Permet de déclencher manuellement l'action

permissions:
  contents: read

env:
  OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Load & install Ollama CLI
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        export PATH="$HOME/.local/bin:$PATH"

    - name: Start Ollama server in background
      run: |
        ps -ef | grep ollama
        ss -ltnp | grep 11434 || true
        # ollama serve &

    - name: Test Ollama
      run: |
        echo "API key length: ${#OLLAMA_API_KEY}"
        env | grep OLLAMA
        ollama run gemma4:cloud --verbose
        ollama --version


    - name: Install uv
      uses: astral-sh/setup-uv@v1

    - run: uv add ollama

    - name: Run main.py
      run: uv run main.py
