# Comments

name: Generate pages and publish

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch: # Permet de déclencher manuellement l'action

permissions:
  contents: read
  pages: write
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:

  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
  
      - name: Install uv
        uses: astral-sh/setup-uv@v1
  
      - run: uv sync
  
      - run: uv run main.py
        env:
          OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
  
      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          sources: ./docs
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3


  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v5
